FROM node:18-alpine

WORKDIR /express-server

COPY package.json ./
COPY .env ./
COPY ./backend ./backend
COPY ./prisma ./prisma

RUN npm install --omit=dev
RUN npx prisma migrate dev

ENV HOSTNAME "0.0.0.0"
EXPOSE 3000

CMD [ "npm", "run", "backend" ]